tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "openssl@1.1"
brew "readline"
brew "unixodbc"
brew "asdf"
brew "gettext", link: false
brew "sqlite"
brew "python"
brew "cmake"
brew "cowsay"
brew "curl"
brew "ffmpeg"
brew "fortune"
brew "git"
brew "libksba"
brew "gnupg"
brew "hub"
brew "imagemagick"
brew "libxslt"
brew "luarocks"
brew "postgresql", restart_service: true
brew "mapnik"
brew "mas"
brew "mysql"
brew "ninja"
brew "nmap"
brew "perl"
brew "pkg-config"
brew "postgis"
brew "redis"
brew "ruby-build"
brew "speedtest-cli"
brew "tidy-html5"
brew "tldr"
brew "trash-cli"
brew "tree"
brew "unzip"
brew "vim"
brew "yarn"
brew "youtube-dl"
brew "z"
brew "zsh"
brew "zsh-completions"
brew "heroku/brew/heroku"
cask "1password"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "postgres"
cask "slack"
cask "visual-studio-code"
mas "Airmail", id: 918858936
mas "Boom 2", id: 948176063
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Kindle", id: 405399194
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
